POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "deyug@gmail.com",
    "password": "ydgusd_78290-d"
}

###

POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "email": "deyug@gmail.com",
    "password": "ydgusd_78290-d"
}

###
DELETE http://localhost:3000/api/auth/users/646bd25cbe227f3e42f6b2c1

###

POST http://localhost:3000/api/sauces/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NDZkYzZiMTM4ZThmM2Q5MzExN2Y2NTIiLCJpYXQiOjE2ODQ5MTU4OTIsImV4cCI6MTY4NDkxOTQ5Mn0.rfeyJbHiF3t6oZDRr2VLBEAtPdnNTpdYI5FiqH_VkPc

{
  "name": "Spicy Tomato Sauce",
  "description": "A delicious and spicy tomato sauce",
  "imageUrl": "https://example.com/sauce.jpg",
  "heatLevel": 3
}