POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "john.doe2@outlook.com",
    "password": "Cc123456789ù%"
}

###

POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "email": "john.doe2@outlook.com",
    "password": "Cc123456789ù%"
}

###
DELETE http://localhost:3000/api/auth/delete/6472541e1385bd7124cb35fe

###

GET http://localhost:3000/api/sauces/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDcyNTQxZTEzODViZDcxMjRjYjM1ZmUiLCJpYXQiOjE2ODUyMTQyNDcsImV4cCI6MTY4NTIxNzg0N30.SP2Sc7dFJ7CMWFgz24iMFL5nlVLjghe6T7Hqj6_e1N4

###

POST http://localhost:3000/api/sauces/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDcwN2U0NmQxOGY5M2QxNDI5MWJjZGYiLCJpYXQiOjE2ODUwOTUwOTgsImV4cCI6MTY4NTA5ODY5OH0.wyVLr256cmJ2Qs89uCQq3MOlT7wdblKHAWzJdVyAt-0

{
  "name": "Spicy Tomato Sauce",
  "description": "A delicious and spicy tomato sauce",
  "imageUrl": "https://example.com/sauce.jpg",
  "heatLevel": 3
}

###

DELETE  http://localhost:3000/api/sauces/647086f45b0c9af333f0f2da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDcwN2U0NmQxOGY5M2QxNDI5MWJjZGYiLCJpYXQiOjE2ODUxMDAxOTksImV4cCI6MTY4NTEwMzc5OX0.vUVcRC7WFEniyneZnL-Lwwn5DTMl7rhYbeWGu5AGCZE