POST http://localhost:3000/api/v1/authentications/signup
Content-Type: application/json

{
    "email": "deyug@gmail.com",
    "password": "ydgusd_78290-d"
}

###

POST http://localhost:3000/api/v1/authentications/login/
Content-Type: application/json

{
    "email": "deyug@gmail.com",
    "password": "ydgusd_78290-d"
}

###
DELETE http://localhost:3000/api/v1/authentications/users/646bb53194f41d0a250eb5de


